name: bootloader-build

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  bootloader-build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/uart_bootloader_stm32
        lfs: true

    - name: Download Repos
      run: |
        git submodule update --init --recursive

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: false
        provenance: false

    - name: Bootloader Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/Bootloader && ./build.sh"

    - name: Application Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/Application && ./build.sh"

    - name: FW Writer Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/Tool && make"
